import type { KBEntry } from "../types";

const ERRORS_DOC = "https://elevenlabs.io/docs/eleven-api/resources/errors";
const AUTH_DOC = "https://elevenlabs.io/docs/api-reference/authentication";
const WS_DOC = "https://elevenlabs.io/docs/conversational-ai/libraries/web-sockets";
const LAST_VERIFIED = "2026-07-04";

const authentication: KBEntry[] = [
  {
    id: "invalid_api_key",
    title: "Invalid API key",
    errorCode: "invalid_api_key",
    httpStatus: 401,
    category: "authentication",
    severity: "high",
    description: "The provided API key is invalid.",
    likelyCauses: [
      "The API key was regenerated/rotated and the client is still using the old value",
      "The key was copied with extra whitespace or truncated",
      "The key belongs to a different workspace/environment than the one being called",
    ],
    remediationSteps: [
      "Confirm the exact key in use by checking Profile Settings → API Keys in the ElevenLabs dashboard",
      "Regenerate the key if it was compromised or its status is unclear, and update it via an environment variable rather than hardcoding",
      "Verify there is no leading/trailing whitespace or line break in the stored key",
    ],
    relatedDocs: [{ label: "Authentication", url: AUTH_DOC }],
    keywords: ["401", "invalid_api_key", "unauthorized", "bad api key"],
    surface: ["rest", "websocket"],
    lastVerified: LAST_VERIFIED,
  },
  {
    id: "missing_api_key",
    title: "Missing API key",
    errorCode: "missing_api_key",
    httpStatus: 401,
    category: "authentication",
    severity: "high",
    description: "No API key was provided in the request.",
    likelyCauses: [
      "The `xi-api-key` header was omitted from the request",
      "The client library was initialized without an API key",
    ],
    remediationSteps: [
      "Ensure every request sets the `xi-api-key` header (or the equivalent SDK client option)",
      "Check that the environment variable holding the key is actually loaded at runtime",
    ],
    relatedDocs: [{ label: "Authentication", url: AUTH_DOC }],
    keywords: ["401", "missing_api_key", "no api key", "xi-api-key"],
    surface: ["rest", "websocket"],
    lastVerified: LAST_VERIFIED,
  },
  {
    id: "invalid_authorization_header",
    title: "Invalid authorization header",
    errorCode: "invalid_authorization_header",
    httpStatus: 401,
    category: "authentication",
    severity: "medium",
    description: "The Authorization header format is incorrect.",
    likelyCauses: [
      "Using a `Bearer` prefix where ElevenLabs expects a raw `xi-api-key` header instead",
      "Header name typo or incorrect casing enforced by a proxy/gateway",
    ],
    remediationSteps: [
      "Use the `xi-api-key` header exactly as documented, not a generic `Authorization: Bearer` scheme",
      "Check any API gateway or proxy in front of the client for header rewriting",
    ],
    relatedDocs: [{ label: "Authentication", url: AUTH_DOC }],
    keywords: ["401", "authorization header", "bearer token"],
    surface: ["rest"],
    lastVerified: LAST_VERIFIED,
  },
  {
    id: "unauthorized",
    title: "Unauthorized",
    errorCode: "unauthorized",
    httpStatus: 401,
    category: "authentication",
    severity: "medium",
    description: "Authentication is required to access this resource.",
    likelyCauses: ["No valid credentials were supplied at all for an endpoint that requires them"],
    remediationSteps: [
      "Attach a valid API key to the request",
      "Confirm the endpoint being called actually requires authentication (some public endpoints do not)",
    ],
    relatedDocs: [{ label: "Authentication", url: AUTH_DOC }],
    keywords: ["401", "unauthorized"],
    surface: ["rest"],
    lastVerified: LAST_VERIFIED,
  },
  {
    id: "sign_in_required",
    title: "Sign-in required",
    errorCode: "sign_in_required",
    httpStatus: 401,
    category: "authentication",
    severity: "low",
    description: "The user must complete the sign-in procedure.",
    likelyCauses: ["A session-based (dashboard) flow is being called without an active browser session"],
    remediationSteps: ["Have the user sign in via the ElevenLabs dashboard before retrying the action"],
    relatedDocs: [{ label: "Authentication", url: AUTH_DOC }],
    keywords: ["401", "sign_in_required", "session expired"],
    surface: ["rest"],
    lastVerified: LAST_VERIFIED,
  },
  {
    id: "forbidden",
    title: "Forbidden",
    errorCode: "forbidden",
    httpStatus: 403,
    category: "authentication",
    severity: "medium",
    description: "Access to this resource is forbidden.",
    likelyCauses: ["The authenticated account does not have access to the requested resource"],
    remediationSteps: [
      "Confirm which workspace/account owns the resource being accessed",
      "Check the API key belongs to the same workspace as the resource",
    ],
    relatedDocs: [{ label: "Errors reference", url: ERRORS_DOC }],
    keywords: ["403", "forbidden"],
    surface: ["rest"],
    lastVerified: LAST_VERIFIED,
  },
  {
    id: "insufficient_permissions",
    title: "Insufficient permissions",
    errorCode: "insufficient_permissions",
    httpStatus: 403,
    category: "authentication",
    severity: "medium",
    description: "The user lacks the required access permissions.",
    likelyCauses: ["The API key belongs to a workspace member with a restricted role"],
    remediationSteps: [
      "Have a workspace admin grant the required role/permission to the member",
      "Use an API key generated by an account with sufficient privileges",
    ],
    relatedDocs: [{ label: "Errors reference", url: ERRORS_DOC }],
    keywords: ["403", "insufficient_permissions", "role"],
    surface: ["rest"],
    lastVerified: LAST_VERIFIED,
  },
  {
    id: "workspace_access_denied",
    title: "Workspace access denied",
    errorCode: "workspace_access_denied",
    httpStatus: 403,
    category: "authentication",
    severity: "medium",
    description: "The user cannot access the specified workspace.",
    likelyCauses: ["The API key's account is not a member of the target workspace"],
    remediationSteps: [
      "Confirm the workspace ID in the request matches a workspace the account belongs to",
      "Ask a workspace admin to invite the account if it should have access",
    ],
    relatedDocs: [{ label: "Errors reference", url: ERRORS_DOC }],
    keywords: ["403", "workspace_access_denied"],
    surface: ["rest"],
    lastVerified: LAST_VERIFIED,
  },
  {
    id: "voice_access_denied",
    title: "Voice access denied",
    errorCode: "voice_access_denied",
    httpStatus: 403,
    category: "authentication",
    severity: "medium",
    description: "The user lacks access to the specified voice.",
    likelyCauses: ["Attempting to use a private/cloned voice belonging to another account or workspace"],
    remediationSteps: [
      "Confirm the voice_id belongs to the calling account's voice library",
      "Share or re-clone the voice under the correct account if cross-account use is intended",
    ],
    relatedDocs: [{ label: "Errors reference", url: ERRORS_DOC }],
    keywords: ["403", "voice_access_denied", "voice_id"],
    surface: ["rest"],
    lastVerified: LAST_VERIFIED,
  },
  {
    id: "model_access_denied",
    title: "Model access denied",
    errorCode: "model_access_denied",
    httpStatus: 403,
    category: "authentication",
    severity: "medium",
    description: "The user cannot access the specified model.",
    likelyCauses: ["The account's subscription tier does not include access to the requested model"],
    remediationSteps: [
      "Check which models are included in the account's current plan",
      "Upgrade the plan or switch to a model included in the current tier",
    ],
    relatedDocs: [{ label: "Errors reference", url: ERRORS_DOC }],
    keywords: ["403", "model_access_denied"],
    surface: ["rest"],
    lastVerified: LAST_VERIFIED,
  },
  {
    id: "subscription_required",
    title: "Subscription required",
    errorCode: "subscription_required",
    httpStatus: 403,
    category: "authentication",
    severity: "medium",
    description: "A paid subscription is needed for this feature.",
    likelyCauses: ["The account is on the free tier and is calling a paid-only feature/endpoint"],
    remediationSteps: ["Upgrade the account to a paid plan that includes the feature being used"],
    relatedDocs: [{ label: "Errors reference", url: ERRORS_DOC }],
    keywords: ["403", "subscription_required", "paid plan"],
    surface: ["rest"],
    lastVerified: LAST_VERIFIED,
  },
  {
    id: "feature_not_available",
    title: "Feature not available on current tier",
    errorCode: "feature_not_available",
    httpStatus: 403,
    category: "authentication",
    severity: "low",
    description: "The feature is unavailable on the account's current subscription tier.",
    likelyCauses: ["The account plan does not include the requested feature (e.g. certain voice cloning tiers)"],
    remediationSteps: ["Check the plan comparison in the dashboard and upgrade if the feature is needed"],
    relatedDocs: [{ label: "Errors reference", url: ERRORS_DOC }],
    keywords: ["403", "feature_not_available"],
    surface: ["rest"],
    lastVerified: LAST_VERIFIED,
  },
];

const rateLimit: KBEntry[] = [
  {
    id: "rate_limit_exceeded",
    title: "Rate limit exceeded",
    errorCode: "rate_limit_exceeded",
    httpStatus: 429,
    category: "rate_limit",
    severity: "medium",
    description: "Too many requests were made in a short period. Wait before retrying.",
    likelyCauses: [
      "The client is issuing requests faster than the plan's per-minute rate limit allows",
      "A retry loop without backoff is amplifying the original request volume",
    ],
    remediationSteps: [
      "Implement exponential backoff and retry on 429 responses",
      "Batch or throttle requests client-side to stay under the plan's rate limit",
      "Consider upgrading to a higher tier if sustained volume requires it",
    ],
    relatedDocs: [{ label: "Errors reference", url: ERRORS_DOC }],
    keywords: ["429", "rate_limit_exceeded", "too many requests"],
    surface: ["rest"],
    lastVerified: LAST_VERIFIED,
  },
  {
    id: "concurrent_limit_exceeded",
    title: "Concurrent request limit exceeded",
    errorCode: "concurrent_limit_exceeded",
    httpStatus: 429,
    category: "rate_limit",
    severity: "medium",
    description:
      "The maximum number of concurrent requests has been exceeded. Free allows 2, Starter 3, Creator 5, Pro 10, Scale/Business 15 concurrent requests.",
    likelyCauses: [
      "Multiple simultaneous TTS/streaming requests are in flight from the same account beyond the plan's concurrency limit",
    ],
    remediationSteps: [
      "Queue requests client-side so concurrency stays within the plan limit",
      "Upgrade to a higher tier for a larger concurrency allowance",
      "Confirm the app isn't leaking open streaming connections that never close",
    ],
    relatedDocs: [{ label: "Errors reference", url: ERRORS_DOC }],
    keywords: ["429", "concurrent_limit_exceeded", "concurrency"],
    surface: ["rest", "websocket"],
    lastVerified: LAST_VERIFIED,
  },
  {
    id: "system_busy",
    title: "System busy",
    errorCode: "system_busy",
    httpStatus: 429,
    category: "rate_limit",
    severity: "low",
    description: "The system is temporarily overloaded; this typically resolves with backoff and retry.",
    likelyCauses: ["Temporary platform-side congestion, not specific to the calling account"],
    remediationSteps: [
      "Retry with exponential backoff",
      "If it persists across many minutes, check the ElevenLabs status page and escalate with the request_id",
    ],
    relatedDocs: [{ label: "Errors reference", url: ERRORS_DOC }],
    keywords: ["429", "system_busy"],
    surface: ["rest"],
    lastVerified: LAST_VERIFIED,
  },
];

const quotaBilling: KBEntry[] = [
  {
    id: "insufficient_credits",
    title: "Insufficient credits",
    errorCode: "insufficient_credits",
    httpStatus: 402,
    category: "quota_billing",
    severity: "high",
    description: "The account lacks sufficient credits/characters for the requested operation.",
    likelyCauses: [
      "The monthly character quota has been exhausted before the billing cycle resets",
      "A one-off large request (e.g. dubbing a long video) exceeds remaining balance",
    ],
    remediationSteps: [
      "Check Profile → Usage in the dashboard to confirm characters used vs. plan limit and reset date",
      "Upgrade the plan or purchase additional credits if available",
      "Split large jobs to fit within the remaining quota until the cycle resets",
    ],
    relatedDocs: [{ label: "Errors reference", url: ERRORS_DOC }],
    keywords: ["402", "insufficient_credits", "quota", "out of characters"],
    surface: ["rest"],
    lastVerified: LAST_VERIFIED,
  },
];

const validation: KBEntry[] = [
  {
    id: "text_too_long",
    title: "Text too long",
    errorCode: "text_too_long",
    httpStatus: 400,
    category: "validation",
    severity: "medium",
    description: "The provided text exceeds the maximum allowed length.",
    likelyCauses: ["The input text/document exceeds the per-request character limit for the endpoint or model"],
    remediationSteps: [
      "Split the request into smaller chunks under the documented character limit",
      "Confirm which model is in use, as character limits vary by model",
    ],
    relatedDocs: [{ label: "Errors reference", url: ERRORS_DOC }],
    keywords: ["400", "text_too_long", "character limit"],
    surface: ["rest"],
    lastVerified: LAST_VERIFIED,
  },
  {
    id: "text_too_short",
    title: "Text too short",
    errorCode: "text_too_short",
    httpStatus: 400,
    category: "validation",
    severity: "low",
    description: "The text length is below the minimum threshold.",
    likelyCauses: ["An empty or near-empty string was sent after trimming whitespace"],
    remediationSteps: ["Validate input length client-side before submitting the request"],
    relatedDocs: [{ label: "Errors reference", url: ERRORS_DOC }],
    keywords: ["400", "text_too_short"],
    surface: ["rest"],
    lastVerified: LAST_VERIFIED,
  },
  {
    id: "invalid_text",
    title: "Invalid text",
    errorCode: "invalid_text",
    httpStatus: 400,
    category: "validation",
    severity: "medium",
    description: "The text contains invalid characters or a malformed structure.",
    likelyCauses: ["Unsupported control characters, broken encoding, or malformed SSML-like markup in the input"],
    remediationSteps: [
      "Sanitize/normalize the text encoding (UTF-8) before sending",
      "Remove unsupported markup or escape special characters as documented",
    ],
    relatedDocs: [{ label: "Errors reference", url: ERRORS_DOC }],
    keywords: ["400", "invalid_text"],
    surface: ["rest"],
    lastVerified: LAST_VERIFIED,
  },
  {
    id: "empty_text",
    title: "Empty text",
    errorCode: "empty_text",
    httpStatus: 400,
    category: "validation",
    severity: "low",
    description: "The text field cannot be empty.",
    likelyCauses: ["A required text field was sent as an empty string or omitted"],
    remediationSteps: ["Ensure the text field is populated before submitting the request"],
    relatedDocs: [{ label: "Errors reference", url: ERRORS_DOC }],
    keywords: ["400", "empty_text"],
    surface: ["rest"],
    lastVerified: LAST_VERIFIED,
  },
  {
    id: "invalid_parameters",
    title: "Invalid parameters",
    errorCode: "invalid_parameters",
    httpStatus: 400,
    category: "validation",
    severity: "medium",
    description: "One or more request parameters are invalid. Check the `param` property in the error response.",
    likelyCauses: ["A parameter value is out of the accepted range, wrong type, or an unrecognized enum value"],
    remediationSteps: [
      "Inspect the `param` field in the error's `detail` object to identify the offending field",
      "Cross-check the value against the endpoint's request schema in the API reference",
    ],
    relatedDocs: [{ label: "Errors reference", url: ERRORS_DOC }],
    keywords: ["400", "invalid_parameters", "validation_error"],
    surface: ["rest"],
    lastVerified: LAST_VERIFIED,
  },
  {
    id: "missing_required_field",
    title: "Missing required field",
    errorCode: "missing_required_field",
    httpStatus: 400,
    category: "validation",
    severity: "medium",
    description: "A required request field is absent. Check the `param` property for the field name.",
    likelyCauses: ["The client omitted a required field, often after an API version change added a new requirement"],
    remediationSteps: [
      "Check the `param` field in the error response for the missing field name",
      "Compare the request payload against the current API reference for that endpoint",
    ],
    relatedDocs: [{ label: "Errors reference", url: ERRORS_DOC }],
    keywords: ["400", "missing_required_field"],
    surface: ["rest"],
    lastVerified: LAST_VERIFIED,
  },
  {
    id: "invalid_voice_settings",
    title: "Invalid voice settings",
    errorCode: "invalid_voice_settings",
    httpStatus: 400,
    category: "validation",
    severity: "low",
    description: "The voice settings object contains invalid values.",
    likelyCauses: ["Stability/similarity/style values outside the 0-1 range, or an unsupported settings combination"],
    remediationSteps: ["Clamp voice settings values to the documented valid ranges before sending"],
    relatedDocs: [{ label: "Errors reference", url: ERRORS_DOC }],
    keywords: ["400", "invalid_voice_settings", "stability", "similarity_boost"],
    surface: ["rest"],
    lastVerified: LAST_VERIFIED,
  },
  {
    id: "invalid_voice_id",
    title: "Invalid voice ID format",
    errorCode: "invalid_voice_id",
    httpStatus: 400,
    category: "validation",
    severity: "medium",
    description: "The voice ID format is malformed.",
    likelyCauses: ["A truncated, copy-pasted-with-typo, or wrong-type identifier was sent as voice_id"],
    remediationSteps: ["Re-copy the voice_id from the dashboard or the Get Voices API response"],
    relatedDocs: [{ label: "Errors reference", url: ERRORS_DOC }],
    keywords: ["400", "invalid_voice_id"],
    surface: ["rest"],
    lastVerified: LAST_VERIFIED,
  },
  {
    id: "unsupported_model",
    title: "Unsupported model for this operation",
    errorCode: "unsupported_model",
    httpStatus: 400,
    category: "validation",
    severity: "medium",
    description: "The requested model is not supported for this operation.",
    likelyCauses: ["Using a TTS-only model ID on an endpoint that requires a different model family (e.g. STT, dubbing)"],
    remediationSteps: ["Check the endpoint's documentation for which model IDs it accepts"],
    relatedDocs: [{ label: "Errors reference", url: ERRORS_DOC }],
    keywords: ["400", "unsupported_model", "model_id"],
    surface: ["rest"],
    lastVerified: LAST_VERIFIED,
  },
  {
    id: "invalid_audio",
    title: "Invalid or corrupted audio",
    errorCode: "invalid_audio",
    httpStatus: 400,
    category: "validation",
    severity: "medium",
    description: "The provided audio is invalid or corrupted.",
    likelyCauses: ["A truncated upload, a non-audio file mislabeled as audio, or a corrupted encode"],
    remediationSteps: [
      "Verify the file plays correctly locally before upload",
      "Re-export/re-encode the audio with a standard codec (e.g. PCM WAV or standard MP3) and retry",
    ],
    relatedDocs: [{ label: "Errors reference", url: ERRORS_DOC }],
    keywords: ["400", "invalid_audio", "corrupted audio"],
    surface: ["rest"],
    lastVerified: LAST_VERIFIED,
  },
  {
    id: "invalid_audio_format",
    title: "Unsupported audio format",
    errorCode: "invalid_audio_format",
    httpStatus: 400,
    category: "validation",
    severity: "medium",
    description: "The specified audio format is not supported.",
    likelyCauses: ["Uploading a codec/container not in the endpoint's supported format list"],
    remediationSteps: ["Convert the audio to one of the documented supported formats before upload"],
    relatedDocs: [{ label: "Errors reference", url: ERRORS_DOC }],
    keywords: ["400", "invalid_audio_format"],
    surface: ["rest"],
    lastVerified: LAST_VERIFIED,
  },
  {
    id: "invalid_output_format",
    title: "Invalid output format requested",
    errorCode: "invalid_output_format",
    httpStatus: 400,
    category: "validation",
    severity: "low",
    description: "The requested output format is not supported.",
    likelyCauses: ["The `output_format` query parameter doesn't match a supported value for the chosen model/plan"],
    remediationSteps: ["Use one of the documented output_format values supported by the model and account tier"],
    relatedDocs: [{ label: "Errors reference", url: ERRORS_DOC }],
    keywords: ["400", "invalid_output_format", "output_format"],
    surface: ["rest"],
    lastVerified: LAST_VERIFIED,
  },
  {
    id: "audio_too_long",
    title: "Audio too long",
    errorCode: "audio_too_long",
    httpStatus: 400,
    category: "validation",
    severity: "medium",
    description: "The audio duration exceeds the maximum limit.",
    likelyCauses: ["Uploading a full-length recording to an endpoint with a short max-duration limit (e.g. voice sample)"],
    remediationSteps: ["Trim the audio to within the documented maximum duration for the endpoint"],
    relatedDocs: [{ label: "Errors reference", url: ERRORS_DOC }],
    keywords: ["400", "audio_too_long"],
    surface: ["rest"],
    lastVerified: LAST_VERIFIED,
  },
  {
    id: "audio_too_short",
    title: "Audio too short",
    errorCode: "audio_too_short",
    httpStatus: 400,
    category: "validation",
    severity: "low",
    description: "The audio duration is below the minimum threshold.",
    likelyCauses: ["A voice sample or clip is too brief to be usable (e.g. under a required minimum for cloning)"],
    remediationSteps: ["Provide a longer audio sample meeting the endpoint's documented minimum duration"],
    relatedDocs: [{ label: "Errors reference", url: ERRORS_DOC }],
    keywords: ["400", "audio_too_short"],
    surface: ["rest"],
    lastVerified: LAST_VERIFIED,
  },
  {
    id: "invalid_file_type",
    title: "Invalid file type",
    errorCode: "invalid_file_type",
    httpStatus: 400,
    category: "validation",
    severity: "low",
    description: "The file type is not supported for this endpoint.",
    likelyCauses: ["Uploading a document/image type not accepted by the endpoint (e.g. wrong MIME type)"],
    remediationSteps: ["Check the endpoint's accepted file types and convert/re-export accordingly"],
    relatedDocs: [{ label: "Errors reference", url: ERRORS_DOC }],
    keywords: ["400", "invalid_file_type"],
    surface: ["rest"],
    lastVerified: LAST_VERIFIED,
  },
  {
    id: "bad_request",
    title: "Bad request",
    errorCode: "bad_request",
    httpStatus: 400,
    category: "validation",
    severity: "low",
    description: "The request could not be understood by the server.",
    likelyCauses: ["A generic malformed request that doesn't fall into a more specific validation category"],
    remediationSteps: ["Compare the full request against the API reference for the endpoint being called"],
    relatedDocs: [{ label: "Errors reference", url: ERRORS_DOC }],
    keywords: ["400", "bad_request"],
    surface: ["rest"],
    lastVerified: LAST_VERIFIED,
  },
  {
    id: "malformed_json",
    title: "Malformed JSON body",
    errorCode: "malformed_json",
    httpStatus: 400,
    category: "validation",
    severity: "low",
    description: "The request body contains invalid JSON structure.",
    likelyCauses: ["A trailing comma, unescaped quote, or client-side serialization bug produced invalid JSON"],
    remediationSteps: ["Validate the JSON payload with a linter/formatter before sending"],
    relatedDocs: [{ label: "Errors reference", url: ERRORS_DOC }],
    keywords: ["400", "malformed_json", "invalid json"],
    surface: ["rest"],
    lastVerified: LAST_VERIFIED,
  },
  {
    id: "request_too_large",
    title: "Request too large",
    errorCode: "request_too_large",
    httpStatus: 400,
    category: "validation",
    severity: "medium",
    description: "The request body exceeds the maximum size allowance.",
    likelyCauses: ["A large base64-encoded audio/image payload pushed the request past the size cap"],
    remediationSteps: [
      "Compress or downsample media before sending",
      "Use a file-upload endpoint (multipart) instead of embedding large base64 blobs in JSON, where available",
    ],
    relatedDocs: [{ label: "Errors reference", url: ERRORS_DOC }],
    keywords: ["400", "request_too_large", "payload too large"],
    surface: ["rest"],
    lastVerified: LAST_VERIFIED,
  },
];

const resourceNotFound: KBEntry[] = [
  {
    id: "voice_not_found",
    title: "Voice not found",
    errorCode: "voice_not_found",
    httpStatus: 404,
    category: "resource_not_found",
    severity: "medium",
    description: "The specified voice ID does not exist.",
    likelyCauses: ["The voice was deleted, belongs to a different account, or the voice_id has a typo"],
    remediationSteps: [
      "Call the Get Voices endpoint to confirm the voice_id is still valid",
      "Verify the voice_id belongs to the account/workspace making the request",
    ],
    relatedDocs: [{ label: "Errors reference", url: ERRORS_DOC }],
    keywords: ["404", "voice_not_found", "voice_id"],
    surface: ["rest"],
    lastVerified: LAST_VERIFIED,
  },
  {
    id: "model_not_found",
    title: "Model not found",
    errorCode: "model_not_found",
    httpStatus: 404,
    category: "resource_not_found",
    severity: "medium",
    description: "The specified model does not exist.",
    likelyCauses: ["A deprecated or misspelled model_id was used"],
    remediationSteps: ["Check the current list of available models via the Get Models endpoint"],
    relatedDocs: [{ label: "Errors reference", url: ERRORS_DOC }],
    keywords: ["404", "model_not_found", "model_id"],
    surface: ["rest"],
    lastVerified: LAST_VERIFIED,
  },
  {
    id: "agent_not_found",
    title: "Conversational AI agent not found",
    errorCode: "agent_not_found",
    httpStatus: 404,
    category: "resource_not_found",
    severity: "medium",
    description: "The specified Conversational AI agent could not be located.",
    likelyCauses: ["The agent_id is wrong, or the agent was deleted/belongs to a different workspace"],
    remediationSteps: [
      "Confirm the agent_id in the Conversational AI dashboard",
      "Check the request is authenticated as the workspace that owns the agent",
    ],
    relatedDocs: [{ label: "WebSocket docs", url: WS_DOC }],
    keywords: ["404", "agent_not_found", "agent_id"],
    surface: ["rest", "websocket"],
    lastVerified: LAST_VERIFIED,
  },
  {
    id: "conversation_not_found",
    title: "Conversation not found",
    errorCode: "conversation_not_found",
    httpStatus: 404,
    category: "resource_not_found",
    severity: "low",
    description: "The specified conversation does not exist.",
    likelyCauses: ["The conversation_id has expired, was purged, or never existed"],
    remediationSteps: ["Confirm the conversation_id was captured correctly at session start and hasn't expired"],
    relatedDocs: [{ label: "WebSocket docs", url: WS_DOC }],
    keywords: ["404", "conversation_not_found"],
    surface: ["rest", "websocket"],
    lastVerified: LAST_VERIFIED,
  },
  {
    id: "phone_number_not_found",
    title: "Phone number not found",
    errorCode: "phone_number_not_found",
    httpStatus: 404,
    category: "resource_not_found",
    severity: "low",
    description: "The specified phone number does not exist.",
    likelyCauses: ["The phone number was not provisioned in the Conversational AI telephony settings, or was removed"],
    remediationSteps: ["Verify the number is provisioned and linked to the correct agent in the dashboard"],
    relatedDocs: [{ label: "Errors reference", url: ERRORS_DOC }],
    keywords: ["404", "phone_number_not_found", "telephony"],
    surface: ["rest"],
    lastVerified: LAST_VERIFIED,
  },
  {
    id: "pronunciation_dictionary_not_found",
    title: "Pronunciation dictionary not found",
    errorCode: "pronunciation_dictionary_not_found",
    httpStatus: 404,
    category: "resource_not_found",
    severity: "low",
    description: "The specified pronunciation dictionary does not exist.",
    likelyCauses: ["The dictionary_id is wrong or the dictionary was deleted"],
    remediationSteps: ["Confirm the dictionary_id via the Get Pronunciation Dictionaries endpoint"],
    relatedDocs: [{ label: "Errors reference", url: ERRORS_DOC }],
    keywords: ["404", "pronunciation_dictionary_not_found"],
    surface: ["rest"],
    lastVerified: LAST_VERIFIED,
  },
  {
    id: "project_not_found",
    title: "Project not found",
    errorCode: "project_not_found",
    httpStatus: 404,
    category: "resource_not_found",
    severity: "low",
    description: "The specified project could not be located.",
    likelyCauses: ["The project_id is wrong or the project was deleted"],
    remediationSteps: ["Confirm the project_id in the Studio/Projects dashboard"],
    relatedDocs: [{ label: "Errors reference", url: ERRORS_DOC }],
    keywords: ["404", "project_not_found"],
    surface: ["rest"],
    lastVerified: LAST_VERIFIED,
  },
  {
    id: "history_item_not_found",
    title: "History item not found",
    errorCode: "history_item_not_found",
    httpStatus: 404,
    category: "resource_not_found",
    severity: "low",
    description: "The specified generation history entry is missing.",
    likelyCauses: ["The history item was deleted, or history retention expired for the account's tier"],
    remediationSteps: ["Check the account's history retention policy and whether the item was manually deleted"],
    relatedDocs: [{ label: "Errors reference", url: ERRORS_DOC }],
    keywords: ["404", "history_item_not_found"],
    surface: ["rest"],
    lastVerified: LAST_VERIFIED,
  },
  {
    id: "user_not_found",
    title: "User not found",
    errorCode: "user_not_found",
    httpStatus: 404,
    category: "resource_not_found",
    severity: "low",
    description: "The user account was not located.",
    likelyCauses: ["Referencing a user_id that doesn't exist, often after account deletion"],
    remediationSteps: ["Confirm the user_id/account still exists in the workspace member list"],
    relatedDocs: [{ label: "Errors reference", url: ERRORS_DOC }],
    keywords: ["404", "user_not_found"],
    surface: ["rest"],
    lastVerified: LAST_VERIFIED,
  },
  {
    id: "knowledge_base_not_found",
    title: "Knowledge base not found",
    errorCode: "knowledge_base_not_found",
    httpStatus: 404,
    category: "resource_not_found",
    severity: "low",
    description: "The specified Conversational AI knowledge base document could not be located.",
    likelyCauses: ["The document_id is wrong, or the document was removed from the agent's knowledge base"],
    remediationSteps: ["Confirm the document is still attached to the agent in the dashboard"],
    relatedDocs: [{ label: "Errors reference", url: ERRORS_DOC }],
    keywords: ["404", "knowledge_base_not_found"],
    surface: ["rest"],
    lastVerified: LAST_VERIFIED,
  },
];

const conflict: KBEntry[] = [
  {
    id: "resource_already_exists",
    title: "Resource already exists",
    errorCode: "resource_already_exists",
    httpStatus: 409,
    category: "conflict",
    severity: "low",
    description: "A resource with the same identifier already exists.",
    likelyCauses: ["A create call was retried after a prior successful create, without checking for existence first"],
    remediationSteps: ["Check whether the resource already exists before creating, or make the create idempotent client-side"],
    relatedDocs: [{ label: "Errors reference", url: ERRORS_DOC }],
    keywords: ["409", "resource_already_exists"],
    surface: ["rest"],
    lastVerified: LAST_VERIFIED,
  },
  {
    id: "voice_already_exists",
    title: "Voice already exists",
    errorCode: "voice_already_exists",
    httpStatus: 409,
    category: "conflict",
    severity: "low",
    description: "A voice with this name was previously created.",
    likelyCauses: ["Attempting to clone a voice using a name that's already taken in the account"],
    remediationSteps: ["Use a unique voice name, or update/delete the existing voice first"],
    relatedDocs: [{ label: "Errors reference", url: ERRORS_DOC }],
    keywords: ["409", "voice_already_exists"],
    surface: ["rest"],
    lastVerified: LAST_VERIFIED,
  },
  {
    id: "already_running",
    title: "Operation already running",
    errorCode: "already_running",
    httpStatus: 409,
    category: "conflict",
    severity: "low",
    description: "The operation is already running.",
    likelyCauses: ["A duplicate job (e.g. dubbing render) was triggered while the first one was still in progress"],
    remediationSteps: ["Poll the existing job's status instead of triggering a second one"],
    relatedDocs: [{ label: "Errors reference", url: ERRORS_DOC }],
    keywords: ["409", "already_running"],
    surface: ["rest"],
    lastVerified: LAST_VERIFIED,
  },
  {
    id: "already_processing",
    title: "Resource already processing",
    errorCode: "already_processing",
    httpStatus: 409,
    category: "conflict",
    severity: "low",
    description: "The resource is currently undergoing processing.",
    likelyCauses: ["A second request was made against a resource mid-processing (e.g. re-training a voice)"],
    remediationSteps: ["Wait for the current processing job to complete before issuing another request"],
    relatedDocs: [{ label: "Errors reference", url: ERRORS_DOC }],
    keywords: ["409", "already_processing"],
    surface: ["rest"],
    lastVerified: LAST_VERIFIED,
  },
  {
    id: "concurrent_modification",
    title: "Concurrent modification conflict",
    errorCode: "concurrent_modification",
    httpStatus: 409,
    category: "conflict",
    severity: "low",
    description: "The resource was modified by another request; retry with the latest version.",
    likelyCauses: ["Two clients (or two tabs/processes) updated the same resource at nearly the same time"],
    remediationSteps: ["Re-fetch the resource's latest state and retry the update"],
    relatedDocs: [{ label: "Errors reference", url: ERRORS_DOC }],
    keywords: ["409", "concurrent_modification"],
    surface: ["rest"],
    lastVerified: LAST_VERIFIED,
  },
  {
    id: "slug_already_exists",
    title: "Slug already exists",
    errorCode: "slug_already_exists",
    httpStatus: 409,
    category: "conflict",
    severity: "low",
    description: "The resource slug identifier is already in use.",
    likelyCauses: ["A human-readable identifier (slug) collides with an existing resource"],
    remediationSteps: ["Choose a different slug or append a disambiguating suffix"],
    relatedDocs: [{ label: "Errors reference", url: ERRORS_DOC }],
    keywords: ["409", "slug_already_exists"],
    surface: ["rest"],
    lastVerified: LAST_VERIFIED,
  },
];

const conversationalAiWebsocket: KBEntry[] = [
  {
    id: "ws_close_1002_protocol_error",
    title: "WebSocket close code 1002 (protocol error)",
    errorCode: "1002",
    httpStatus: null,
    category: "conversational_ai_websocket",
    severity: "high",
    description:
      "The WebSocket connection closed with a protocol error, commonly seen when sending malformed or out-of-order audio chunk messages to a Conversational AI agent session.",
    likelyCauses: [
      "Audio chunks are sent in the wrong message format or before the session handshake completes",
      "The client sends a message type the server doesn't recognize mid-session",
    ],
    remediationSteps: [
      "Confirm the client waits for the initial conversation_initiation_metadata event before streaming audio",
      "Validate outgoing message shapes exactly match the documented WebSocket protocol",
      "Add reconnect-with-backoff logic since transient protocol errors can occur on flaky networks",
    ],
    relatedDocs: [{ label: "WebSocket docs", url: WS_DOC }],
    keywords: ["websocket", "close code 1002", "protocol error", "conversational ai"],
    surface: ["websocket"],
    lastVerified: LAST_VERIFIED,
  },
  {
    id: "ws_close_3000_request_error",
    title: "WebSocket close code 3000 (request error)",
    errorCode: "3000",
    httpStatus: null,
    category: "conversational_ai_websocket",
    severity: "high",
    description:
      "The WebSocket closed immediately with 'Request error' and no further diagnostic detail, often when connecting to a specific agent branch/version.",
    likelyCauses: [
      "The agent_id or conversation signed-URL/token is invalid, expired, or points to a branch/version that no longer exists",
      "A required query parameter (e.g. signed URL expiry) was missing when opening the socket",
    ],
    remediationSteps: [
      "Regenerate the signed WebSocket URL / conversation token right before connecting rather than reusing a cached one",
      "Confirm the agent_id and any branch/version reference are still valid in the dashboard",
      "Capture the request_id (if present in connection response headers) and include it when escalating to ElevenLabs support",
    ],
    relatedDocs: [{ label: "WebSocket docs", url: WS_DOC }],
    keywords: ["websocket", "close code 3000", "request error", "conversational ai"],
    surface: ["websocket"],
    lastVerified: LAST_VERIFIED,
  },
  {
    id: "ws_unexpected_disconnect",
    title: "WebSocket disconnects unexpectedly mid-stream",
    errorCode: "ws_unexpected_disconnect",
    httpStatus: null,
    category: "conversational_ai_websocket",
    severity: "medium",
    description:
      "The connection status moves from connected to disconnected mid-conversation without an explicit close code, sometimes surfacing as 'WebSocket is already in CLOSING or CLOSED state' when a second close/send is attempted.",
    likelyCauses: [
      "Network instability (mobile network handoff, Wi-Fi to cellular) dropped the underlying TCP connection",
      "The client attempted to send audio after the socket had already started closing, without checking readyState",
      "An idle timeout was hit because no audio/keepalive was sent for an extended period",
    ],
    remediationSteps: [
      "Check `readyState` before sending and guard against double-close",
      "Implement automatic reconnect with a short backoff and resume/restart the conversation session",
      "Add a lightweight keepalive if the integration can have long silent gaps",
    ],
    relatedDocs: [{ label: "WebSocket docs", url: WS_DOC }],
    keywords: ["websocket", "disconnect", "closing or closed state", "conversational ai"],
    surface: ["websocket"],
    lastVerified: LAST_VERIFIED,
  },
];

const serverError: KBEntry[] = [
  {
    id: "internal_error",
    title: "Internal server error",
    errorCode: "internal_error",
    httpStatus: 500,
    category: "server_error",
    severity: "critical",
    description: "An unexpected server error occurred on ElevenLabs' side.",
    likelyCauses: ["A transient platform-side fault unrelated to the request contents"],
    remediationSteps: [
      "Retry the request once after a short delay",
      "If it recurs consistently for the same input, capture the request_id and full error body and escalate to team@elevenlabs.io",
    ],
    relatedDocs: [{ label: "Errors reference", url: ERRORS_DOC }],
    keywords: ["500", "internal_error"],
    surface: ["rest"],
    lastVerified: LAST_VERIFIED,
  },
  {
    id: "service_unavailable",
    title: "Service unavailable",
    errorCode: "service_unavailable",
    httpStatus: 503,
    category: "server_error",
    severity: "high",
    description: "The service is temporarily unavailable; this should be a rare occurrence.",
    likelyCauses: ["Platform-wide incident or capacity issue"],
    remediationSteps: [
      "Retry with backoff",
      "Check the ElevenLabs status page for an active incident before escalating",
    ],
    relatedDocs: [{ label: "Errors reference", url: ERRORS_DOC }],
    keywords: ["503", "service_unavailable"],
    surface: ["rest", "websocket"],
    lastVerified: LAST_VERIFIED,
  },
  {
    id: "maintenance",
    title: "Scheduled maintenance",
    errorCode: "maintenance",
    httpStatus: 503,
    category: "server_error",
    severity: "medium",
    description: "Scheduled service maintenance is in progress.",
    likelyCauses: ["The request landed during an announced maintenance window"],
    remediationSteps: ["Check ElevenLabs' status/changelog for announced maintenance windows and retry afterward"],
    relatedDocs: [{ label: "Errors reference", url: ERRORS_DOC }],
    keywords: ["503", "maintenance"],
    surface: ["rest", "websocket"],
    lastVerified: LAST_VERIFIED,
  },
];

export const seedEntries: KBEntry[] = [
  ...authentication,
  ...rateLimit,
  ...quotaBilling,
  ...validation,
  ...resourceNotFound,
  ...conflict,
  ...conversationalAiWebsocket,
  ...serverError,
];
